# Generated by Django 5.0.6 on 2024-06-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Divinity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Le nom principal de la divinité, y compris d'éventuels surnoms ou variantes régionales.",
                        max_length=100,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="Les principaux domaines ou éléments associés à la divinité (e.g., tonnerre, amour, guerre).",
                        max_length=100,
                    ),
                ),
                (
                    "main_symbol",
                    models.CharField(
                        help_text="Un élément ou objet principal associé à la divinité, tel qu'un animal, une plante, ou un objet spécifique.",
                        max_length=100,
                    ),
                ),
                (
                    "associated_myths",
                    models.TextField(
                        help_text="Descriptions des mythes ou légendes les plus connus impliquant la divinité."
                    ),
                ),
                (
                    "characteristics",
                    models.TextField(
                        help_text="Traits principaux ou aspects de la personnalité mythique, par exemple, vengeur, protecteur, sage."
                    ),
                ),
                (
                    "manifestations",
                    models.TextField(
                        help_text="Descriptions des formes que la divinité peut prendre dans les récits mythologiques."
                    ),
                ),
                (
                    "symbolic_animals",
                    models.CharField(
                        help_text="Animaux qui sont fréquemment liés à la divinité dans les mythes ou comme symboles.",
                        max_length=100,
                    ),
                ),
                (
                    "power_objects",
                    models.CharField(
                        help_text="Objets mythiquement significatifs associés à la divinité, tels qu'une arme ou un artefact.",
                        max_length=100,
                    ),
                ),
                (
                    "cultural_role",
                    models.TextField(
                        help_text="Description du rôle de la divinité dans la culture, par exemple, son influence sur l'art, la littérature, ou les pratiques sociales."
                    ),
                ),
                (
                    "festivals",
                    models.TextField(
                        help_text="Mentions de festivals ou célébrations historiquement liés à la divinité, en se concentrant sur leur aspect culturel ou commémoratif."
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        help_text="Région ou culture spécifique d'où la divinité est originaire.",
                        max_length=100,
                    ),
                ),
                (
                    "ethnicity",
                    models.CharField(
                        help_text="Groupe ethnique principalement associé à la divinité.",
                        max_length=100,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Champ pour stocker des images représentatives ou artistiques de la divinité.",
                        null=True,
                        upload_to="divinity_images/",
                    ),
                ),
                (
                    "parents",
                    models.CharField(
                        blank=True,
                        help_text="Noms des parents de la divinité, si applicable.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "descendants",
                    models.CharField(
                        blank=True,
                        help_text="Noms des descendants de la divinité, si applicable.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
