# Generated by Django 5.0.6 on 2024-06-18 11:17

import entities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0002_divinity_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="divinity",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("A", "Androgyn")],
                default="M",
                help_text="Genre de la divinité. Elle peut être féminine, masculine, ou androgyne",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="divinity",
            name="prompt",
            field=models.TextField(
                blank=True,
                help_text="Aggrégation des attributs pour composer le prompt de la génération de l'image du personnage",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="divinity",
            name="status",
            field=models.CharField(
                choices=[("G", "God/Godess"), ("S", "Spirit")],
                default="G",
                help_text="Statut de la divinité. Elle peut être un Dieu, une Déesse ou un Esprit.",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="divinity",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Champ pour stocker des images représentatives ou artistiques de la divinité.",
                null=True,
                upload_to="divinity_images/",
                validators=[entities.models.validate_image],
            ),
        ),
    ]
