# Generated by Django 5.0.6 on 2024-06-23 22:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0003_divinity_gender_divinity_prompt_divinity_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Le nom de la categorie", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Texte qui décrit la catégorie", max_length=100
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="divinity",
            name="status",
        ),
        migrations.AddField(
            model_name="divinity",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="divinity",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="divinity",
            name="image_caption",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Masculin"),
                            ("F", "Féminin"),
                            ("A", "Androgyne"),
                        ],
                        max_length=1,
                    ),
                ),
                ("story", models.TextField()),
                ("country", models.CharField(max_length=100)),
                ("origin", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="hero_images/"),
                ),
                (
                    "image_caption",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heroes",
                        to="entities.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MythicalCreature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("country", models.CharField(max_length=100)),
                ("habitat", models.CharField(max_length=255)),
                ("powers", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="creature_images/"
                    ),
                ),
                (
                    "image_caption",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creatures",
                        to="entities.category",
                    ),
                ),
            ],
        ),
    ]
