# Generated by Django 5.0.6 on 2024-06-24 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0004_category_remove_divinity_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="divinity",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="divinity",
                to="entities.category",
            ),
            preserve_default=False,
        ),
    ]
