# Generated by Django 5.0.6 on 2024-06-25 21:05

import django.db.models.deletion
import entities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0005_divinity_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="achievements",
            field=models.TextField(
                blank=True,
                help_text="Réalisations notables ou exploits du héros.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hero",
            name="allies",
            field=models.TextField(
                blank=True,
                help_text="Alliés ou compagnons du héros dans les mythes.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hero",
            name="enemies",
            field=models.TextField(
                blank=True,
                help_text="Ennemis ou adversaires du héros dans les mythes.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hero",
            name="titles",
            field=models.CharField(
                blank=True,
                help_text="Titres honorifiques ou noms alternatifs du héros.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mythicalcreature",
            name="diet",
            field=models.CharField(
                blank=True,
                help_text="Régime alimentaire de la créature mythique.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mythicalcreature",
            name="size",
            field=models.CharField(
                blank=True,
                help_text="Taille ou dimensions typiques de la créature.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mythicalcreature",
            name="strengths",
            field=models.TextField(
                blank=True,
                help_text="Forces ou capacités spéciales de la créature.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mythicalcreature",
            name="weaknesses",
            field=models.TextField(
                blank=True,
                help_text="Faiblesses ou vulnérabilités de la créature.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="category",
            field=models.ForeignKey(
                help_text="Catégorie à laquelle appartient le héros.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="heroes",
                to="entities.category",
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="country",
            field=models.CharField(
                help_text="Le pays d'origine du héros.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date de création du héros."
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="Date de la dernière mise à jour du héros."
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="gender",
            field=models.CharField(
                choices=[("M", "Masculin"), ("F", "Féminin"), ("A", "Androgyne")],
                help_text="Le genre du héros.",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Champ pour stocker des images représentatives ou artistiques du héros.",
                null=True,
                upload_to="hero_images/",
                validators=[entities.models.validate_image],
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="image_caption",
            field=models.CharField(
                blank=True,
                help_text="Légende descriptive de l'image du héros.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="name",
            field=models.CharField(
                help_text="Le nom principal du héros.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="origin",
            field=models.CharField(
                help_text="La région ou culture spécifique d'où le héros est originaire.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="story",
            field=models.TextField(
                help_text="L'histoire ou les légendes associées au héros."
            ),
        ),
        migrations.AlterField(
            model_name="mythicalcreature",
            name="category",
            field=models.ForeignKey(
                help_text="Catégorie à laquelle appartient la créature mythique.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creatures",
                to="entities.category",
            ),
        ),
        migrations.AlterField(
            model_name="mythicalcreature",
            name="country",
            field=models.CharField(
                help_text="Le pays d'origine de la créature mythique.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="mythicalcreature",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date de création de la créature."
            ),
        ),
        migrations.AlterField(
            model_name="mythicalcreature",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date de la dernière mise à jour de la créature.",
            ),
        ),
        migrations.AlterField(
            model_name="mythicalcreature",
            name="description",
            field=models.TextField(
                help_text="Description détaillée de la créature mythique."
            ),
        ),
        migrations.AlterField(
            model_name="mythicalcreature",
            name="habitat",
            field=models.CharField(
                help_text="L'habitat naturel ou mythologique de la créature.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="mythicalcreature",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Champ pour stocker des images représentatives ou artistiques de la créature.",
                null=True,
                upload_to="creature_images/",
                validators=[entities.models.validate_image],
            ),
        ),
        migrations.AlterField(
            model_name="mythicalcreature",
            name="image_caption",
            field=models.CharField(
                blank=True,
                help_text="Légende descriptive de l'image de la créature.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mythicalcreature",
            name="name",
            field=models.CharField(
                help_text="Le nom principal de la créature mythique.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="mythicalcreature",
            name="powers",
            field=models.TextField(
                help_text="Les pouvoirs ou capacités surnaturelles de la créature."
            ),
        ),
    ]
