# Generated by Django 5.0.6 on 2024-06-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0007_remove_divinity_prompt_hero_descendants_hero_parents"),
    ]

    operations = [
        migrations.AddField(
            model_name="mythicalcreature",
            name="appareance",
            field=models.CharField(
                blank=True,
                help_text="Brêve description de la créature",
                max_length=255,
                null=True,
            ),
        ),
    ]
