# Generated by Django 5.0.6 on 2024-07-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_alter_mythicalcreature_appareance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='country',
            field=models.CharField(blank=True, help_text="Le pays d'origine du héros.", max_length=100, null=True),
        ),
    ]
