# Generated by Django 5.0.6 on 2024-07-30 16:30

import django.contrib.postgres.fields
import django.db.models.deletion
import entities.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_divinity_created_by_hero_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divinity',
            name='associated_myths',
        ),
        migrations.RemoveField(
            model_name='divinity',
            name='festivals',
        ),
        migrations.AddField(
            model_name='divinity',
            name='alignment',
            field=models.CharField(blank=True, help_text='The moral or ethical alignment of the deity, e.g., good, evil, neutral.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='divinity',
            name='conjoint',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text="Name of the deity's spouse or partner, if applicable.", null=True, size=None),
        ),
        migrations.AddField(
            model_name='divinity',
            name='distincts_physicals_signs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text='Distinct physical signs or attributes of the deity. Ex : "turbaned", "masqued", "with a spear", "white beard"', null=True, size=None),
        ),
        migrations.AddField(
            model_name='divinity',
            name='pantheon',
            field=models.CharField(blank=True, help_text='The pantheon or group of deities to which the deity belongs.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='divinity',
            name='region',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text='Specific region or culture from which the deity originates.', null=True, size=None),
        ),
        migrations.AddField(
            model_name='divinity',
            name='story_description',
            field=models.TextField(blank=True, help_text="Description of the deity's story or mythological background.", null=True),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='category',
            field=models.ForeignKey(help_text='The category to which the deity belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='divinities', to='entities.category'),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='characteristics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text='Main traits or aspects of the mythical personality, e.g., vengeful, protective, wise.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='country',
            field=models.CharField(blank=True, help_text='Current country from which the deity originates.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created the deity.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_divinities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='cultural_role',
            field=models.CharField(help_text="Description of the deity's role in the culture, e.g., 'God of Thunder' , 'goddess of love', etc.", max_length=100),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date the deity was created.'),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, help_text='The date the deity was last updated.'),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='descendants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text="Names of the deity's descendants, if applicable.", null=True, size=None),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='domain',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text='The main domains or elements associated with the deity, e.g., thunder, love, war.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='ethnicity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text='Ethnic(s) group(s) primarily associated with the deity.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('F', 'Female'), ('A', 'Androgyn')], help_text='The gender of the divinity', max_length=1),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='image',
            field=models.ImageField(blank=True, help_text='Field to store representative or artistic images of the deity.', null=True, upload_to='divinity_images/', validators=[entities.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='image_caption',
            field=models.CharField(blank=True, help_text="Caption for the deity's image.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='main_symbol',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text='A main element or object associated with the deity, such as an animal, plant, or specific object.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='manifestations',
            field=models.CharField(blank=True, help_text="Descriptions of the forms the deity can take in mythological narratives. e.g: 'beautiful woman wearing jewelry' or 'man often depicted in white outfit'.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='name',
            field=models.CharField(help_text='The main name of the deity, including any nicknames or regional variants.', max_length=100),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='origin',
            field=models.CharField(blank=True, help_text='Specific region or culture from which the deity originates.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='parents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text="Names of the deity's parents, if applicable.", null=True, size=None),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='power_objects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text='Mythically significant objects associated with the deity, such as a weapon or artifact.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='symbolic_animals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text='Animals that are frequently linked to the deity in myths or as symbols.', null=True, size=None),
        ),
    ]
