# Generated by Django 5.0.6 on 2024-08-01 23:22

import entities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0012_remove_divinity_associated_myths_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageWithCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Champ pour stocker des images représentatives ou artistiques de la créature.', null=True, upload_to=entities.models.upload_to, validators=[entities.models.validate_image])),
                ('image_caption', models.CharField(blank=True, help_text="Légende descriptive de l'image de la créature.", max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='divinity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='divinity',
            name='image_caption',
        ),
        migrations.RemoveField(
            model_name='divinity',
            name='region',
        ),
        migrations.AddField(
            model_name='divinity',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Field to store representative or artistic images of the deity.', related_name='divinities', to='entities.imagewithcaption'),
        ),
    ]
